

stages:
#  - test
  - deploy

deploy-job:
  stage: deploy
  image:
    name: gableroux/ansible:4.6.0
  script:
    # https://docs.gitlab.com/ee/ci/ssh_keys/
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh/
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - echo "$ANSIBLE_VAULT_PASS" > ./vault_pass
    - ansible --version
    - ansible-playbook play-deploy-ssh-keys.yml -u ubuntu --extra-vars "target=production" -v -i ./inventory/hosts.yml --vault-password-file ./vault_pass
    - ansible-playbook play-commontools.yml -u ubuntu --extra-vars "target=production" -v -i ./inventory/hosts.yml --vault-password-file ./vault_pass
    - ansible-playbook play-firewall.yml -u ubuntu --extra-vars "target=production" -v -i ./inventory/hosts.yml --vault-password-file ./vault_pass
    - ansible-playbook play-db.yml -u ubuntu --extra-vars "target=dbservers" -v -i ./inventory/hosts.yml --vault-password-file ./vault_pass
    - ansible-playbook play-webapp.yml -u ubuntu --extra-vars "target=appservers" -v -i ./inventory/hosts.yml --vault-password-file ./vault_pass
    - ansible-playbook play-monitoring.yml -u ubuntu --extra-vars "target=monservers" -v -i ./inventory/hosts.yml --vault-password-file ./vault_pass

  only: 
    - main
#  when: manual