# Unison vars

unison_configs:
  - name: sync-wordpress
    src: "{{ app_root_folder }}"
    dest: "ssh://app01/{{ app_root_folder }}"
    ignore:
      - "Path .git/*"
      - "Name *.{log,tmp}"

unison_cron:
  hour: '*'
  minute: '*/5'


# nginx upstreams

nginx_upstreams: 
- name: backend
  strategy: "ip_hash" # "least_conn", etc.
  keepalive: 16 # optional 
  servers: { 
    "127.0.0.1:9000",
    "app01.devopsit.ru:9000 weight=2",
  }