all:
  hosts:
    app01.devopsit.ru:
    app02.devopsit.ru:
    db01.devopsit.ru:
    monitoring.devopsit.ru:
    192.168.229.129:
  children:
    appservers:
      hosts:
        app01.devopsit.ru:
        app02.devopsit.ru:
        192.168.229.129:
    dbservers:
      hosts:
        db01.devopsit.ru:
        192.168.229.129:
    monservers:
      hosts:
        monitoring.devopsit.ru:
    production:
      hosts:
        app01.devopsit.ru:
        app02.devopsit.ru:
        db01.devopsit.ru:
        monitoring.devopsit.ru:
    test:
      hosts:
        192.168.229.129:
