
# mysql_db: "" 
# mysql_user: ""
# mysql_password: "!"

mysql_port: '3306'

mysql_databases:
  - name: "{{ mysql_db }}"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ mysql_user }}"
    host: "%"
    password: "{{ mysql_password }}"
    priv: "wordpress.*:ALL"