---
- name: Install & enable ufw & allow ssh on 22 port 
  block:
    - name: Install ufw 
      apt: 
        name: ufw
    - name: Allow ssh through firewall
      ufw:
        rule: allow 
        proto: tcp
        port: '22'
    - name: Set ufw policy
      ufw: 
        state: enabled
        direction: incoming 
        policy: deny
  tags: 
    - ufw

- name: Allow http & https
  block:
    - name: Allow access http
      ufw: 
        rule: allow
        port: "{{ app_http_port }}"
        proto: tcp
    - name: Allow access https
      ufw: 
        rule: allow
        port: "{{ app_https_port }}"
        proto: tcp
  when: "'appservers' in group_names"
  tags:
  - ufw_allow_web

- name: Allow access to mysql
  ufw:
   rule: allow
   port: "{{ mysql_port }}"
   proto: tcp
  when: "'dbservers' in group_names"
  tags:
    - ufw_allow_mysql

- name: Allow access to prometheus
  ufw:
   rule: allow
   port: "{{ prometheus_http }}"
   proto: tcp
  when: "'monservers' in group_names"
  tags:
    - ufw_allow_prometheus_http

- name: Allow access to alertmanager
  block:
    - name: Allow all access to alertmanager custom http port
      ufw: 
        rule: allow
        port: "{{ alert_manager_http }}"
        proto: tcp
    - name: Allow all access to custom port tcp 
      ufw: 
        rule: allow
        port: "{{ alert_manager }}"
        proto: tcp
    - name: Allow all access to custom port udp 
      ufw: 
        rule: allow
        port: "{{ alert_manager }}"
        proto: udp
  when: "'monservers' in group_names"
  tags:
  - ufw_allow_alertmanager

- name: Allow access to node_exporter
  ufw:
   rule: allow
   port: "{{ node_exporter }}"
   proto: tcp
  when: "'monservers' in group_names"
  tags:
    - ufw_allow_node_exporter


- name: Allow access to grafana
  ufw:
   rule: allow
   port: "{{ grafana }}"
   proto: tcp
  when: "'monservers' in group_names"
  tags:
    - ufw_allow_grafana