---
- name: Install & enable ufw & allow ssh on 22 port 
  block:
    - name: Install ufw 
      apt: 
        name: ufw
    - name: Allow ssh through firewall
      ufw:
        rule: allow 
        proto: tcp
        port: '22'
    - name: Set ufw policy
      ufw: 
        state: enabled
        direction: incoming 
        policy: deny
  tags: 
    - ufw

- name: Allow access http
  ufw: 
    rule: allow
    port: "{{ app_http_port }}"
    proto: tcp
  when: app_http_port is defined
  tags:
  - ufw_allow_web

- name: Allow access https
  ufw: 
    rule: allow
    port: "{{ app_https_port }}"
    proto: tcp
  when: app_https_port is defined
  tags:
  - ufw_allow_web

- name: Allow access fastcgi
  ufw: 
    rule: allow
    port: "{{ app_fastcgi }}"
    proto: tcp
  when: app_fastcgi is defined
  tags:
  - ufw_allow_web

- name: Allow to collect nginx_stub_metrics
  ufw: 
    rule: allow
    port: "{{ nginx_stub_metrics }}"
    proto: tcp
  when: nginx_stub_metrics is defined
  tags:
  - ufw_allow_nginx_stub_metrics


- name: Allow access to mysql
  ufw:
   rule: allow
   port: "{{ mysql_port }}"
   proto: tcp
  when: mysql_port is defined
  tags:
    - ufw_allow_mysql

- name: Allow access to mysqld_exporter
  ufw:
   rule: allow
   port: "{{ mysqld_exporter }}"
   proto: tcp
  when: mysqld_exporter is defined
  tags:
    - ufw_allow_mysqld_exporter


- name: Allow access to prometheus
  ufw:
   rule: allow
   port: "{{ prometheus_http }}"
   proto: tcp
  when: prometheus_http is defined
  tags:
    - ufw_allow_prometheus_http

- name: Allow all access to alertmanager custom http port
  ufw: 
    rule: allow
    port: "{{ alert_manager_http }}"
    proto: tcp
  when: alert_manager_http is defined
  tags:
  - ufw_allow_alertmanager

- name: Allow all access to custom port tcp 
  ufw: 
    rule: allow
    port: "{{ alert_manager }}"
    proto: tcp
  when: alert_manager is defined
  tags:
  - ufw_allow_alertmanager
- name: Allow all access to custom port udp 
  ufw: 
    rule: allow
    port: "{{ alert_manager }}"
    proto: udp
  when: alert_manager is defined
  tags:
  - ufw_allow_alertmanager

- name: Allow access to node_exporter
  ufw:
   rule: allow
   port: "{{ node_exporter_tcp }}"
   proto: tcp
  when: node_exporter_tcp is defined
  tags:
    - ufw_allow_node_exporter

- name: Allow access to InfluxDB
  ufw:
   rule: allow
   port: "{{ influxdb_tcp }}"
   proto: tcp
  when: influxdb_tcp is defined
  tags:
    - ufw_allow_InfluxDB


- name: Allow access to grafana
  ufw:
   rule: allow
   port: "{{ grafana_tcp }}"
   proto: tcp
  when: grafana_tcp is defined
  tags:
    - ufw_allow_grafana